config/routes.rb
Rails.application.routes.draw do
  # get 'subtasks/new'
  # get 'subtasks/create'
  # get 'subtasks/edit'
  # get 'subtasks/update'
  # get 'subtasks/destroy'
  # get 'tasks/index'
  # get 'tasks/show'
  # get 'tasks/new'
  # get 'tasks/create'
  # get 'tasks/edit'
  # get 'tasks/update'
  # get 'tasks/destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tasks#index"
  resources :tasks do
    resources :subtasks
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/subtask.rb
class Subtask < ApplicationRecord
  belongs_to :task

  # validates :subtask_name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
    has_many :subtasks, dependent: :destroy

    # validates :task_name, presence: true
    # validates :due_date, presence: true
    # validates :project, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # skip_before_action :verify_authenticity_token
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController
  before_action :set_task
  before_action :set_subtask, only: [:edit, :update]

  def index
    @subtasks = @task.subtasks
    # render json: { data: @subtasks }, status: :ok
  end
  
  def show

  end

  def new
    @subtask = @task.subtasks.build
  end

  def create
    @subtask = @task.subtasks.build(subtask_params)
    if @subtask.save
      pp @subtask
      redirect_to task_subtasks_path(@task)
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @subtask.update(subtask_params)
      redirect_to task_subtasks_path(@task)
    else
      render :edit
    end
  end

  def destroy
    @subtask.destroy
    redirect_to task_subtasks_path(@task)
  end

  private

  def set_task
    @task = Task.find(params[:task_id])
  end

  def set_subtask
    @subtask = @task.subtasks.find(params[:id])
  end

  def subtask_params
    params.require(:subtask).permit(:subtask_name)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
    # render json: { data: @tasks }, status: :ok
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new
    if @task.save
      redirect_to @task
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to @task
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:task_name, :due_date, :project)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subtasks_helper.rb
module SubtasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subtasks/create.html.erb
<h1>Subtasks#create</h1>
<p>Find me in app/views/subtasks/create.html.erb</p>
<h1>New Sub Task</h1>

<%= form_with(model: @subtask, url: task_subtasks_path) do |form| %>
  <%= form.label :task_name %>
  <%= form.text_field :subtask_name %>
  <%= form.submit %>
<% end %>

<p><%= link_to "Cancel", tasks_path %></p>

app/views/subtasks/destroy.html.erb
<h1>Subtasks#destroy</h1>
<p>Find me in app/views/subtasks/destroy.html.erb</p>

app/views/subtasks/edit.html.erb
<h1>Subtasks#edit</h1>
<p>Find me in app/views/subtasks/edit.html.erb</p>

app/views/subtasks/new.html.erb
<h1>Subtasks#new</h1>
<p>Find me in app/views/subtasks/new.html.erb</p>
<h1>New Sub Task</h1>

<%= form_with(model: @subtask, url: task_subtasks_path) do |form| %>
  <%= form.label :task_name %>
  <%= form.text_field :subtask_name %>
  <%= form.submit %>
<% end %>

<p><%= link_to "Cancel", tasks_path %></p>

app/views/subtasks/update.html.erb
<h1>Subtasks#update</h1>
<p>Find me in app/views/subtasks/update.html.erb</p>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

<%= form_with(model: @task, local: true) do |form| %>
    <%= form.label :task_name %>
    <%= form.text_field :task_name %>
    <%= form.label :due_date %>
    <%= form.date_field :due_date %>
    <%= form.label :project %>
    <%= form.text_field :project %>
    <%= form.submit %>
  <% end %>
  
  <p><%= link_to "Cancel", tasks_path %></p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
# <p>Find me in app/views/tasks/index.html.erb</p>

<h1>Tasks</h1>

<h1>All Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= link_to task.task_name, task %>

      <% if task.subtasks.any? %>
        <ul>
          <% task.subtasks.each do |subtask| %>
            <li><%= subtask.subtask_name %></li>
          <% end %>
        </ul>
      <% end %>
    </li>
  <% end %>
</ul>

<p><%= link_to "New Task", new_task_path %></p>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_with(model: @task, local: true) do |form| %>
  <%= form.label :task_name %>
  <%= form.text_field :task_name %>
  <%= form.label :due_date %>
  <%= form.date_field :due_date %>
  <%= form.label :project %>
  <%= form.text_field :project %>
  <%= form.submit %>
<% end %>

<p><%= link_to "Cancel", tasks_path %></p>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>

<h1><%= @task.task_name %></h1>

<% if @task.subtasks.any? %>
  <h3>Subtasks:</h3>
  <ul>
    <% @task.subtasks.each do |subtask| %>
      <li><%= subtask.subtask_name %></li>
    <% end %>
  </ul>
<% end %>

<p><%= link_to "Edit", edit_task_path(@task) %></p>
<p><%= link_to "Delete", @task, method: :delete, data: { confirm: 'Are you sure?' } %></p>
<p><%= link_to "New Subtask", new_task_subtask_path(@task) %></p>
<p><%= link_to "All Tasks", tasks_path %></p>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>